#!/usr/bin/env bash
# Prints "To infinity and beyond" every 2 seconds and reacts to SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done

